theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  plausible: lesveteransduweb.org
  posts:
    index:
      layout: grid
  debug:
     productionUrl: "https://www.lesveteransduweb.org"